### PR TITLE
small clean-up of audioled.serverconfiguration

### PR DESCRIPTION
**Pull request by ChasonDeshotel**
The second two commits should have been on a different branch, sorry. They're all on the same file so I didn't think it warranted rolling back my local repo

First commit: fixed bug when output device does not exist  (createOutputDevice() tried to return an uninitialized variable and croaked, now returns None as you would expect)

Other commits: Prevented rehashing of dictionaries and simplified a few things for readability

### CODE REVIEW

**Comment by ChasonDeshotel** [comment]
And I have a conflict, great, my fork must have been behind. This is my first go at a collaborative project on GitHub, bear with me. If you want to close or deny this pull request I can fix it and make a new one. Thanks

**Comment by ChasonDeshotel** [comment]
>I've split the createOutputDevice() into _createOrReuseOutputDevice and a public createOutputDevice. This would be reverted and should be fixed.

Right, I must have branched before that commit, I didn't notice there were merge conflicts until after I made the pull request. Pretty sure I fixed that with [72fa8fc](https://github.com/segfault16/modular-led-controller-workstation/pull/105/commits/72fa8fc4adce57491bbf466d368dbef37fc73d9d) above. I pushed that after the initial request

> can you try configuring your IDE to use yapf and the style .style.yapf?

Sure, I'd be happy to

> The commas at the beginning of the line look ugly to me ;)

Yes but I can spot missing commas from a mile away :) Actually I like it better, but that's how I was taught years and years ago, that's what I'm used to, and I rarely forget a comma with them up front. No biggie though, consistent style is more important

**Comment by ChasonDeshotel** [comment]
Using that style, yapf is doing some interesting things, like..

```
         if self._activeProject is not None and key in [
-                CONFIG_NUM_PIXELS,
-                CONFIG_DEVICE,
-                CONFIG_DEVICE_CANDY_SERVER,
-                CONFIG_NUM_ROWS,
+                CONFIG_NUM_PIXELS, CONFIG_DEVICE, CONFIG_DEVICE_CANDY_SERVER, CONFIG_NUM_ROWS,
                 CONFIG_DEVICE_PANEL_MAPPING
```

I just ran `yapf --style ../.style.yapf -i serverconfiguration.py`. Is that .style.yapf up to date or am I doing something wrong?

Thanks

**Comment by segfault16** [comment]
Just updated yapf styling on master and added a trailing comma. I've formatted this manually before, thanks for the hint ;)

**Comment by ChasonDeshotel** [comment]
@segfault16 see if that works for you. Sorry to be a pain. Hopefully yapf is acting how you like so we can avoid all of this in the future. Thanks

**Comment by segfault16** [comment]
Hey @ChasonDeshotel,
it's all good - git, forks and merge conflicts can really be a bitch.
I've updated your branch with our master, I think you missed that.
This is a good read if you're working on a fork:
https://help.github.com/en/articles/syncing-a-fork

**Pull request merged**
