### PR TITLE
Modulators

### PR DESCRIPTION
**Pull request by segfault16**
This PR adds support for modulating parameters of effects 🎉

A new type of nodes can be added to the FilterGraph that represents ModulationSources. 
By adding a connection between a ModulationSource and the parameter of a Effect Node - a Modulation - the ModulationSource is able to update the parameter value of a Effect Node by adding a positive or negative offset. Offsets are defined to be in the range [0,1] and are scaled to the range of the parameter as defined in the parameter definition.

One ModulationSource can drive an arbitrary number of parameters of different Effects. For each of those Modulations you can specify an amount and if the adjustment of the parameter should be adjusted in positive or negative direction.

I think this enables quite a lot of possibilities, e.g. implementing Performance Parameters described in #125.

ToDo's:
- [x] Edit Popup for ModulationSources to adjust the parameter
- [x] Update `getParameter()` of Effect to return the original value. Currently returns the adjusted value by modulation.
- [x] Show Edit Popup for Modulation after drawing the edge
- [x] Show Modulations in Edit Popup for ModulationSources?
- [x] Show Modulations in Edit Popup for Effects?
- [x] ~~Use separate API (and screen?) for adding ModulationSources since right now it's quite hidden~~ (Autocomplete as a super fast way for filtering for modulations)
- [x] Adjust layout and node visualisation for ModulationSources
- [x] Adjust effects that can't handle modulations right now

Merge after #131 and #132.
Merge after #140 and #141.

### CODE REVIEW

**Comment by segfault16** [comment]
@fruechtegott 
This is quite an early stage, I'd love to hear your feedback.

For now to test this new feature:
- Add a new node `audioled.modulation.ExternalLinearController` and set the `offset` to 1 (there is no edit for Modulators atm
- In order to drive a parameter, draw an edge from the modulator to an effect
- Click on the edge to edit the Modulation: Select a parameter and an amount. Changing the amount should change the parameter value

**Comment by segfault16** [comment]
@fruechtegott 
I've updated the effects for modulations. No need to check each effect I think. Please review PR.

**Comment by segfault16** [comment]
@fruechtegott 

> * Values for the Modulation Destinations in Modulation Source so I can adjust two effects equally and do not have to guess what value I picked for the first one. (See following point)

Valid point. Once a modulator is added all settings can then be edited via ModulationSource Popup.
> * Connecting a modulator to a modulator should work. Raises "connections can only be added from output to input"

Cool request, won't do that in this PR though. Pls create a separate issue for this.
> * When connecting a modulator to an effect but not selecting a 
parameter, the connection should not be established, when leaving the connection window. Right now you get an empty connection

I'll look into it.

> * Connection more than one modulator to an effect should be more visible

Don't get it

**Comment by segfault16** [comment]
@fruechtegott 

Can you create issues for the points:


>
> 
> > * Values for the Modulation Destinations in Modulation Source so I can adjust two effects equally and do not have to guess what value I picked for the first one. (See following point)
> 
> Valid point. Once a modulator is added all settings can then be edited via ModulationSource Popup.
> 

and 

> > * When connecting a modulator to an effect but not selecting a
> >   parameter, the connection should not be established, when leaving the connection window. Right now you get an empty connection
> 
> I'll look into it.

Can't prioritise this right now. Can you create separate issues and approve the PR, since I think the feature is stable and initially functional. Other stuff is just optional improvements.

I'd rather work on #125 or #139.

**Comment by fruechtegott** [comment]
Issues are up as requested. 
Do you want to merge now?

**Comment by segfault16** [comment]
@fruechtegott Jap

**Pull request merged**
