### PR TITLE
WIP: Multi outputs

### LINKED ISSUE #79: Support multiple LED Outputs
The LED Output Effect currently has only one channel to send pixels to. For more advanced setups controlled by a single device there should be a number of channels in the LED Output Effect.
Server configuration has to be adjusted in order to send pixel information from different channels to multiple devices, e.g. different CandyServers.

### LINKED ISSUE #104: Decouple effect processing and LED output
Performance shows that we can process the FilterGraph at high framerates even with a lot of LEDs. However the bottleneck currently is sending the LED data out, see also #100. A type of framebuffer could be implemented, where we process the next frame while sending the LED data out in a separate process.

### LINKED ISSUE #139: Proposal: Multi-Device output
As for now we're able to drive one LED output at a time.
For more complex scenarios where one Raspberry should drive multiple LED strips I propose the following changes:

## Configurable output section
Add a configurable output section where the user can define multiple outputs, so that one device can drive multiple LED strips, panels or other remote devices via OPC. 
For example three outputs:
- 300 Pixel via GPIO as output 1
- 200 Pixel via Serial port as output 2
- 500 Pixel via OPC to remote device as output 3
This configuration is independent of Projects and Filtergraphs

## Update Perform Page
On the perform page add scenes that can be switched via Midi, UI or other remote control systems. The user is able to configure for each scene which slot of the Project will be activated for a specific device.
This way, we can keep the current datastructure with Projects and Filtergraphs for slots in the Project and Projects can still be exchanged independently of a specific device configuration.

## Make Project slots and scenes more distinguishable
I propose to use the Piano component only for switching between scenes and come up with a new visualization for Project slots.

## Adjust Edit page
Since on the Edit page we're editing one Filtergraph, we shouldn't switch scenes here. Add a configuration for a `preview device` which will render the current Filtergraph in Edit mode.

## Render multiple Filtergraphs
Of course we need to adjust the render code so we can actually render multiple Filtergraphs in parallel (also the same Filtergraph with different devices which can mean different number of pixels per device)

### PR DESCRIPTION
**Pull request by segfault16**
Rewriting the output section with multithreading allowing multiple FilterGraph instanced to render independently.

- [x] Separate Filtergraph instance in process, communication via multiprocessing.JoinableQueue and implementation of event mechanism in Filtergraph
- [x] Error handling for the above
- [x] Implement solution for sub-device (e.g. same strip: device1 then device2)
- [x] Update configuration GUI for devices
- [x] Test a lot 🦄 🌟  🎉 

This PR resolves #139, resolves #79 and resolves #104

### CODE REVIEW

**Comment by segfault16** [comment]
@fruechtegott Can you please have a look at this? Changing output configuration via GUI doesn't work on RaspberryPi, but I think I can't resolve this.. Probably some issue with the library and multiprocessing

**Comment by segfault16** [comment]
@fruechtegott Fixed the string/int bug

**Comment by segfault16** [comment]
@fruechtegott Now only slots for the actual devices are shown in Edit View. Added also some documentation on output configuration in the UI.
For future reference:

A simple single device configuration:
single_output

For configuring multiple slots on the same HW LED device:
multi_output
The two virtual output slots in output group `twoInOne` will be combined into a single array by output group `oneStrip` and sent to the FadeCandy server.

For independent output devices you can also simply add multiple independent devices to one output group:
multi_device

**Comment by fruechtegott** [comment]
Scene matrix works.

New bug appeared: When switching active device from non-multi-outputs to multi-outputs.
With last working server config and 10 virtual outputs:
Bildschirmfoto 2020-04-22 um 17 56 10

Test config. 2 virtual devices:
Bildschirmfoto 2020-04-22 um 19 00 03

Project config:
[conf.txt](https://github.com/segfault16/modular-led-controller-workstation/files/4517778/conf.txt)

Would really like to merge. You are not making this easy for me.

**Comment by segfault16** [comment]
The problem is that you’re trying to have the same CandyServer on multiple slots of the scene. Each port can only be used once. If you want multiple servers you have to configure a separate FilterGraph on each slot with CandyServers listening on different ports.

**Pull request merged**
